### ISSUE TITLE
Zephyr (Zenith - RPG Series compat)

### ISSUE THREAD

**Issue by OneWorldStudio** [muon-rw/Zephyr#1]
Hello, can you please make BetterCombat optional, I use EpicFight + Connector, and would like to use your mod in my build, thanks for earlier

**Comment by muon-rw** [comment]
Sure, I’ll probably separate out the better combat section into a Fabric version of Apothic Combat.

**Comment by OneWorldStudio** [comment]
Okay, thank you so much

**Comment by muon-rw** [comment]
Made Better Combat (and Jewelry) optional in fb2a900, which is included in version 0.3.0.
Should be approved soon on CF and Modrinth!
