### ISSUE TITLE
Aternos Availability

### ISSUE THREAD

**Issue by a-lakeside-viewer** [muon-rw/Zephyr#12]
Greetings! I would like to inquire on if this was intentional. I would like to play with this mod alongside my friends again but when I looked for it in Aternos it was no longer there and when I went to the 'Suggest a mod/plugin' it was denied (see attached). I saw no Issues similar to this so I assumed the topic has yet to be discussed. I would appreciate clarification on the issue if it is not too much of a bother (and, if acceptable, it being reinstated in Aternos). Thank you very much!

![image](https://github.com/user-attachments/assets/c11dc73b-8c04-4230-b945-a5fabf233cb3)

**Comment by muon-rw** [comment]
It’s a Curseforge setting - Fixed now, you’ll probably just need to request it again.
