### ISSUE TITLE
AttributesLib attributes can not be used in SpellEngine or Jewelry configs

### ISSUE THREAD

**Issue by Ozbobo** [muon-rw/Zephyr#2]
Trying to use Jewels with Apotheosis and Zephyr but Minecraft Keeps crashing on startup. I made sure to add "apotheosis": "zenith" to the connector.json config. I have isolated the mods to make sure it was these mods that were conflicting. I sent the same report over to the Sinytra Connector github.

Minecraft Version: 1.20.1
Forge Version: 47.2.0

Crash Report: 
[crash-2024-04-04_10.31.50-client.txt](https://github.com/muon-rw/Zephyr/files/14872793/crash-2024-04-04_10.31.50-client.txt)

Mods in use: 
![Mods1](https://github.com/muon-rw/Zephyr/assets/166033943/648dc6cd-b182-4251-83f9-a30c213c02a5)
![Mods2](https://github.com/muon-rw/Zephyr/assets/166033943/b004c3a6-f271-42ab-81a3-5d1e45e1e734)

**Comment by muon-rw** [comment]
Hi, can you see if this issue persists after switching to the latest Neoforge or Forge 47.1.3?

If it still doesn’t work this is probably a Connector issue, as our mixin into Jewelry has no problems on Fabric.

**Comment by Ozbobo** [comment]
Yes, the issue is the same. I already made a post about it in the Connector github. Now we just wait I guess. Thanks for your quick response :)

**Comment by muon-rw** [comment]
I have implemented a workaround in 0.4.0 that will prevent crashing, however, AttributesLib attributes aren't currently able to be added to Jewelry/Spell Engine item configs.
