### ISSUE TITLE
Zephyr ignores connector name alias with Sinytra beta.42 / Forgified Fabric API 0.92.1

### ISSUE THREAD

**Issue by Kegare** [muon-rw/Zephyr#5]
Game pretty much crashes into ingame error report. With just Zephyr installed, it asks for Zenith, with both Zephyr & Zenith installed (alongside Apotheosis, without Zenith's dependencies) game just asks for all of Zenith's dependencies.

**Comment by muon-rw** [comment]
Could you send a screenshot of the exact message?

**Comment by Kegare** [comment]
Sure thing, thanks for quick reply! Here it is:
With both Zephyr and Zenith installed:
![image](https://github.com/muon-rw/Zephyr/assets/4334513/816639cb-180f-46b1-bf2c-a146440af1af)
crash log: https://pastebin.com/7wA3QFec
With just Zephyr installed:
![image](https://github.com/muon-rw/Zephyr/assets/4334513/ad07811f-9541-4dcd-9d2b-1c9377ee870c)
crash log: https://pastebin.com/zmE5zJk8
In both cases there was Apotheosis installed, latest Sinytra & Forgified fabric + Sinytra extras. Ofcourse, alias was added to config (as I already stated). Hope this helps!

**Comment by muon-rw** [comment]
Can you show the exact contents of your connector.json config file?

**Comment by Kegare** [comment]
Absolutely.
{
  "version": 1,
  "hiddenMods": [],
  "globalModAliases": {
    "cloth_config": "cloth-config2",
    "playeranimator": "player-animator",
    "apotheosis": "zenith"
  }
}

**Comment by muon-rw** [comment]
Seems to be working for me now on Connector 44
