### ISSUE TITLE
Improper Projectile Damage For Archer Series Bows

### ISSUE THREAD

**Issue by Atsumachi** [muon-rw/Zephyr#6]
Minecraft: **1.20.1**
Fabric Loader: **0.15.11**
Fabric API: **0.92.1+1.20.1**

Zenith: **1.1.9-1.20.1**
Zenith Attributes: **0.2.4**
Zephyr: **v0.4.1+1.20.1**
Archers (RPG Series): **v1.2.1+1.20.1**
Ranged Weapon API: **v1.1.1+1.20.1**

**Issue:**
- When reforging any of the bows added from Archers (RPG Series), if a bow rolls a Projectile Damage attribute, it lowers the damage output of the bow massively. 
![image](https://github.com/muon-rw/Zephyr/assets/89116003/faf9d153-076d-4ca5-badc-e0094545eacf)
![output2 webm_snapshot_00 35_ 2024 05 20_23 01 32](https://github.com/muon-rw/Zephyr/assets/89116003/6557e008-6b84-4c46-89ed-469f07b24832)
![image](https://github.com/muon-rw/Zephyr/assets/89116003/99f2ac1c-bc31-4aa4-921f-7f4c952fa049)
![output2 webm_snapshot_00 32_ 2024 05 20_23 01 13](https://github.com/muon-rw/Zephyr/assets/89116003/38e411a7-6d52-4685-80cd-423167460396)

**Reproduction:**
- Reforge any bow that's added by Archers (RPG Series) and roll for a "Projectile Damage" attribute.

**Comment by muon-rw** [comment]
There are two bugs here: 
- 0.31 is a percent multiplier amount but is being applied with the addition operation, oops!
- Ranged Weapon API and Projectile Damage’s attributes should *not* be interacting this way. While I can and will switch everything over to `ranged_weapon:damage`, that bug should really be reported to Daedelus

**Comment by Atsumachi** [comment]
> There are two bugs here:
> 
>     * 0.31 is a percent multiplier amount but is being applied with the addition operation, oops!
> 
>     * Ranged Weapon API and Projectile Damage’s attributes should _not_ be interacting this way. While I can and will switch everything over to `ranged_weapon:damage`, that bug should really be reported to Daedelus

Thank you for taking a look at this, I'll get this reported to Daedelus as well.

**Comment by muon-rw** [comment]
I just checked and we had already switched all instances of Projectile Damage to Ranged Weapon Damage in a version before what you posted. 

Did you possibly have an out of date datapack?

**Comment by muon-rw** [comment]
not a me issue ™️
